spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karmanov/gaia-config
  application:
    name: config-service
server:
  port: 10101

eureka:
  client:
    service-url.defaultZone: http://localhost:10100/eureka/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
